[network]
n3h_path = "/home/eric/code/metacurrency/holochain/n3h"
n3h_persistence_path = "/tmp"
bootstrap_nodes = []

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "sandwich--------------------------------------------------------------------------AAAEqzh28L"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "bagel-----------------------------------------------------------------------------AAADAq0mCu"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent3"
name = "HoloTester3"
public_address = "croissant-------------------------------------------------------------------------AAAEuHzxV4"
key_file = "holo_tester.key"

[[dnas]]
id = "holochat_dna"
file = "bundle.json"
hash = "Qm328wyq38924y"


[[instances]]
id = "test-instance1"
dna = "holochat_dna"
agent = "test_agent1"
[instances.storage]
type = "file"
path = "tmp-storage"

[[instances]]
id = "test-instance2"
dna = "holochat_dna"
agent = "test_agent2"
[instances.storage]
type = "file"
path = "tmp-storage2"


[[interfaces]]
id = "websocket_interface1"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "test-instance1"

[[interfaces]]
id = "websocket_interface2"
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "test-instance2"

[logger]
type = "debug"
  [[logger.rules.rules]]
    pattern = "^err/"
    color = "red"
  [[logger.rules.rules]]
    pattern = "^debug/dna"
    color = "white"
  [[logger.rules.rules]]
    pattern = ".*"
